### PR TITLE
Net Standard 2.0

### PR DESCRIPTION
**Pull request by nicolaiarocci**
This is a rather big change. 

- Net Standard 2.0
- Update test project to new API version of xBehave (and update all dependencies to latest releases)
- Drop the strong naming

Moving to Net Standard 2.0 implies dropping support for older .NET versions, such as 4.0, 4.5.x, and 4.6.0 (will do fine with 4.6.1+).

### CODE REVIEW

**Comment by SuperJMN** [comment]
Please, merge!

**Comment by SuperJMN** [comment]
@jamesfoster Are you there?

**Comment by ErikSchierboom** [comment]
This would be very convenient!

**Comment by dkmiller** [comment]
Any reason this hasn't merged?

**Comment by nicolaiarocci** [comment]
Given the strong demand, I could release from a fork. Not ideal, and I'd prefer to avoid that (besides, I'd be hard-pressed to find a better name than DeepEqual 😄 ).

**Comment by allrameest** [comment]
@nicolaiarocci I think forking would be a good idea. I've tried emailing James but I didn't get an answer.
About the name... DeeperEqual? DeepestEqual? 😄

**Comment by SuperJMN** [comment]
I packaged it and posted (.NET Standard): https://www.nuget.org/packages/DeepEqual.SuperJMN/

**Comment by jamesfoster** [comment]
Apologies for the absence 🤕. Finally closing this. Version 1.7.1 is now multi-targeted to 4.6.2, standard 2.0, core 2.1

Thanks @SuperJMN for stepping up and helping out. Much appreciated.

**Comment by SuperJMN** [comment]
Thanks, @jamesfoster !

**Pull request closed without merging**
